server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
mybatis:
  type-aliases-package: com.ling.springboot02.dao